install.packages('KoNLP')
install.packages('SnowballC')
install.packages('wordcloud')
install.packages('RColorBrewer')
install.packages('plyr')
install.packages('stringr')
install.packages('ggplot2')

library(KoNLP)
library(SnowballC)
library(RColorBrewer)
library(wordcloud) 
library(plyr)
library(stringr)
library(ggplot2)
useSejongDic()
getwd()

txt <- readLines("./Project/R_Project/crawl/data/all_rank.txt", encoding = "EUC-KR")
word_by_word <- readLines("./Project/R_Project/crawl/data/all_rank_without_blank.txt")
teen <- readLines("././Project/R_Project/crawl/data/teen.txt")
twenty <- readLines("././Project/R_Project/crawl/data/twenty.txt")
thirty <- readLines("././Project/R_Project/crawl/data/thirty.txt")
fourty <- readLines("././Project/R_Project/crawl/data/fourty.txt")
fifty <- readLines("././Project/R_Project/crawl/data/fifty.txt")
teen_divide <- readLines("././Project/R_Project/crawl/data/teen_divide.txt")
twenty_divide <- readLines("././Project/R_Project/crawl/data/twenty_divide.txt")
thirty_divide <- readLines("././Project/R_Project/crawl/data/thirty_divide.txt")
fourty_divide <- readLines("././Project/R_Project/crawl/data/fourty_divide.txt")
fifty_divide <- readLines("././Project/R_Project/crawl/data/fifty_divide.txt")

actual_keyword <- str_replace_all(txt, " ", "")
teen <- str_replace_all(teen, " ", "")
twenty <- str_replace_all(twenty, " ", "")
thirty <- str_replace_all(thirty, " ", "")
fourty <- str_replace_all(fourty, " ", "")
fifty <- str_replace_all(fifty, " ", "")

wordcount_whole_keyword <- table(unlist(actual_keyword))
wordcount_seperated_keyword <- table(unlist(word_by_word))
wordcount_teen_keyword <- table(unlist(teen))
wordcount_twenty_keyword <- table(unlist(twenty))
wordcount_thirty_keyword <- table(unlist(thirty))
wordcount_fourty_keyword <- table(unlist(fourty))
wordcount_fifty_keyword <- table(unlist(fifty))
wordcount_teen_divide_keyword <- table(unlist(teen_divide))
wordcount_twenty_divide_keyword <- table(unlist(twenty_divide))
wordcount_thirty_divide_keyword <- table(unlist(thirty_divide))
wordcount_fourty_divide_keyword <- table(unlist(fourty_divide))
wordcount_fifty_divide_keyword <- table(unlist(fifty_divide))

df_wordcount_whole_keyword <- as.data.frame(wordcount_whole_keyword, stringsAsFactors = F)
df_wordcount_seperated_keyword <- as.data.frame(wordcount_seperated_keyword, stringsAsFactors = F)
df_wordcount_teen_keyword <- as.data.frame(wordcount_teen_keyword, stringsAsFactors = F)
df_wordcount_twenty_keyword <- as.data.frame(wordcount_twenty_keyword, stringsAsFactors = F)
df_wordcount_thirty_keyword <- as.data.frame(wordcount_thirty_keyword, stringsAsFactors = F)
df_wordcount_fourty_keyword <- as.data.frame(wordcount_fourty_keyword, stringsAsFactors = F)
df_wordcount_fifty_keyword <- as.data.frame(wordcount_fifty_keyword, stringsAsFactors = F)
df_wordcount_teen_divide_keyword <- as.data.frame(wordcount_teen_divide_keyword, stringsAsFactors = F)
df_wordcount_twenty_divide_keyword <- as.data.frame(wordcount_twenty_divide_keyword, stringsAsFactors = F)
df_wordcount_thirty_divide_keyword <- as.data.frame(wordcount_thirty_divide_keyword, stringsAsFactors = F)
df_wordcount_fourty_divide_keyword <- as.data.frame(wordcount_fourty_divide_keyword, stringsAsFactors = F)
df_wordcount_fifty_divide_keyword <- as.data.frame(wordcount_fifty_divide_keyword, stringsAsFactors = F)

df_wordcount_whole_keyword <- df_wordcount_whole_keyword %>%  arrange(desc(Freq))
df_wordcount_seperated_keyword <- df_wordcount_seperated_keyword %>% arrange(desc(Freq))
df_wordcount_teen_keyword <- df_wordcount_teen_keyword %>% arrange(desc(Freq))
df_wordcount_twenty_keyword <- df_wordcount_twenty_keyword %>% arrange(desc(Freq))
df_wordcount_thirty_keyword <- df_wordcount_thirty_keyword %>% arrange(desc(Freq))
df_wordcount_fourty_keyword <- df_wordcount_fourty_keyword %>% arrange(desc(Freq))
df_wordcount_fifty_keyword <- df_wordcount_fifty_keyword %>% arrange(desc(Freq))
df_wordcount_teen_divide_keyword <- df_wordcount_teen_divide_keyword %>% arrange(desc(Freq))
df_wordcount_twenty_divide_keyword <- df_wordcount_twenty_divide_keyword %>% arrange(desc(Freq))
df_wordcount_thirty_divide_keyword <- df_wordcount_thirty_divide_keyword %>% arrange(desc(Freq))
df_wordcount_fourty_divide_keyword <- df_wordcount_fourty_divide_keyword %>% arrange(desc(Freq))
df_wordcount_fifty_divide_keyword <- df_wordcount_fifty_divide_keyword %>% arrange(desc(Freq))

View(df_wordcount_whole_keyword)
View(df_wordcount_seperated_keyword)
View(df_wordcount_teen_keyword)
View(df_wordcount_twenty_keyword)
View(df_wordcount_thirty_keyword)
View(df_wordcount_fourty_keyword)
View(df_wordcount_fifty_keyword)
View(df_wordcount_teen_divide_keyword)
View(df_wordcount_twenty_divide_keyword)
View(df_wordcount_thirty_divide_keyword)
View(df_wordcount_fourty_divide_keyword)
View(df_wordcount_fifty_divide_keyword)

require(devtools)
library(wordcloud2)

wordcloud2(data = df_wordcount_whole_keyword, figPath = "./Project/R_Project/naver.png", color= c("#3de52d"), backgroundColor="white")
wordcloud2(data = df_wordcount_seperated_keyword, figPath = "./Project/R_Project/Naver_1.png", color="#3de52d", backgroundColor="white")

wordcloud2(data = df_wordcount_teen_keyword, figPath = "./Project/R_Project/teen.png", color=rep_len(c("#ede574", "#f9d423","#fc913a","#ff4e50"), nrow(df_wordcount_teen_keyword)), backgroundColor="black")
wordcloud2(data = df_wordcount_twenty_keyword, figPath = "./Project/R_Project/twenty.png", color=rep_len(c("#285943", "#77AF9C","#8CD790","#519D9E"), nrow(df_wordcount_twenty_keyword)), backgroundColor="black")
wordcloud2(data = df_wordcount_thirty_keyword, figPath = "./Project/R_Project/thirty.png", color=rep_len(c("#00dffc", "#008c9e","#005f6b","#aacfd0"), nrow(df_wordcount_thirty_keyword)), backgroundColor="black")
wordcloud2(data = df_wordcount_fourty_keyword, figPath = "./Project/R_Project/fourty.png", color=rep_len(c("#f6ea8c", "#f26d5b","#c03546","#492540"), nrow(df_wordcount_fourty_keyword)), backgroundColor="black")
wordcloud2(data = df_wordcount_fifty_keyword, figPath = "./Project/R_Project/fifty.png", color=rep_len(c("#D499B9", "#9055A2","#2E294E","#011638"), nrow(df_wordcount_fifty_keyword)), backgroundColor="white")


wordcloud2(data = df_wordcount_teen_divide_keyword, figPath = "./Project/R_Project/teen.png", color=rep_len(c("#ede574", "#f9d423","#fc913a","#ff4e50"), nrow(df_wordcount_teen_divide_keyword)), backgroundColor="black")
wordcloud2(data = df_wordcount_twenty_divide_keyword, figPath = "./Project/R_Project/twenty.png", color=rep_len(c("#285943", "#77AF9C","#8CD790","#519D9E"), nrow(df_wordcount_twenty_divide_keyword)), backgroundColor="black")
wordcloud2(data = df_wordcount_thirty_divide_keyword, figPath = "./Project/R_Project/thirty.png", color=rep_len(c("#00dffc", "#008c9e","#005f6b","#aacfd0"), nrow(df_wordcount_thirty_divide_keyword)), backgroundColor="black")
wordcloud2(data = df_wordcount_fourty_divide_keyword, figPath = "./Project/R_Project/fourty.png", color=rep_len(c("#f6ea8c", "#f26d5b","#c03546","#492540"), nrow(df_wordcount_fourty_divide_keyword)), backgroundColor="black")
wordcloud2(data = df_wordcount_fifty_divide_keyword, figPath = "./Project/R_Project/fifty.png", color=rep_len(c("#D499B9", "#9055A2","#2E294E","#011638"), nrow(df_wordcount_fifty_divide_keyword)), backgroundColor="white")